"""add quests and test_cases tables

Revision ID: 268a67d63e2f
Revises: ae9e5b7b20fa
Create Date: 2026-05-25 18:52:19.293924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268a67d63e2f'
down_revision = 'ae9e5b7b20fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('example_solution', sa.Text(), nullable=True),
    sa.Column('language', sa.Enum('python', 'javascript', 'java', 'csharp', name='language'), nullable=False),
    sa.Column('difficulty', sa.Enum('initiate', 'adept', 'archmage', name='difficulty'), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quest_id', 'index', name='uq_quest_testcase_index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_cases')
    op.drop_table('quests')
    # ### end Alembic commands ###
