"""add achievements and user_achievements tables

Revision ID: 63d38862ecae
Revises: 3c4d5e6f7a8b
Create Date: 2026-08-01 20:25:14.143167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d38862ecae'
down_revision = '3c4d5e6f7a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('job', 'process', 'test_suite', 'general', name='achievement_category'), nullable=False),
    sa.Column('glyph', sa.String(length=8), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('criteria_type', sa.Enum('job_completions', 'process_challenges', 'test_run_completions', 'test_run_perfect_score', 'total_xp', 'level', 'rank', 'has_avatar', 'job_comments_count', 'jobs_authored_count', name='achievement_criteria_type'), nullable=False),
    sa.Column('criteria_params', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    # NOTE: autogenerate also proposed dropping ix_test_runs_user_id — that's
    # pre-existing drift unrelated to achievements (TestRun.user_id was never
    # declared index=True in the model, despite the DB having had the index
    # since the original trivia_sessions migration), left alone here.


def downgrade():
    op.drop_table('user_achievements')
    op.drop_table('achievements')
