"""add avatar total_xp and quest_completions

Revision ID: 93410b598318
Revises: 3f1a9c82b04e
Create Date: 2026-05-30 20:59:34.175440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93410b598318'
down_revision = '3f1a9c82b04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quest_id', name='uq_user_quest_completion')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('total_xp', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_xp')
        batch_op.drop_column('avatar')

    op.drop_table('quest_completions')
    # ### end Alembic commands ###
