"""add bosses and boss_challenges tables

Revision ID: 96bb92136a5e
Revises: 93410b598318
Create Date: 2026-05-31 22:26:25.691592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96bb92136a5e'
down_revision = '93410b598318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bosses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('avatar', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('specialty', sa.String(length=200), nullable=False),
    sa.Column('difficulty', sa.Enum('cursed', 'damned', 'infernal', name='bossdifficulty'), nullable=False),
    sa.Column('aura', sa.Text(), nullable=False),
    sa.Column('lore', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('boss_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('challenge_text', sa.Text(), nullable=False),
    sa.Column('boss_taunt', sa.Text(), nullable=False),
    sa.Column('user_solution', sa.Text(), nullable=True),
    sa.Column('boss_verdict', sa.Text(), nullable=True),
    sa.Column('technical_feedback', sa.Text(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('score_pct', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'failed', name='challengestatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boss_id'], ['bosses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boss_challenges')
    op.drop_table('bosses')
    # ### end Alembic commands ###
